# Récit : la vitesse sol du SR-71 (histoire racontée par le pilote Brian Shul dans « Sled Driver » ;
# indicatif Aspen 20, navigateur Walter Watson ; Cessna 90 kt, Twin Beech 125 kt, F/A-18 « Dusty 52 » 620 kt, SR-71 1 842 kt ; 1 842 kt = 3 412 km/h)
SCENES = [
    dict(type='hook', score=(0, 0), title="LA RÉPONSE RADIO LA PLUS LÉGENDAIRE DE L'AVIATION",
         say="C'est la réponse radio la plus légendaire de l'histoire de l'aviation. Et elle est vraie. Écoute bien la fin.",
         show="C'est la réponse radio la plus légendaire de l'histoire de l'aviation. Et elle est vraie. Écoute bien la fin."),
    dict(type='story', score=(0, 0), img='sr_side', badge="SR-71 · 24 KM D'ALTITUDE",
         say="Un SR soixante et onze survole la Californie, à vingt-quatre kilomètres d'altitude. Aux commandes, Brian Shul. Derrière lui, son navigateur, Walter.",
         show="Un SR-71 survole la Californie, à 24 km d'altitude. Aux commandes, Brian Shul. Derrière lui, son navigateur, Walter."),
    dict(type='story', score=(0, 0), img='sr71', badge="PLUS DE MACH 3",
         say="Le SR soixante et onze, c'est l'avion à réaction le plus rapide jamais construit. Plus de trois fois la vitesse du son, si haut qu'on voit la courbure de la Terre.",
         show="Le SR-71, c'est l'avion à réaction le plus rapide jamais construit. Plus de 3 fois la vitesse du son, si haut qu'on voit la courbure de la Terre."),
    dict(type='radio', score=(0, 0), who="CESSNA", img='c172', kt=90, n=0,
         say="Sur la fréquence de Los Angeles, un petit Cessna demande sa vitesse sol. Réponse du contrôleur : quatre-vingt-dix nœuds.",
         show="Sur la fréquence de Los Angeles, un petit Cessna demande sa vitesse sol. Réponse du contrôleur : 90 nœuds."),
    dict(type='radio', score=(0, 0), who="BIMOTEUR", img=None, kt=125, n=1,
         say="Un bimoteur demande la même chose. Cent vingt-cinq nœuds.",
         show="Un bimoteur demande la même chose. 125 nœuds."),
    dict(type='radio', score=(0, 0), who="CHASSEUR DE LA NAVY", img=None, kt=620, n=2,
         say="Puis un pilote de chasse de la Navy, en F A dix-huit, demande à son tour, d'une voix très sûre de lui. Six cent vingt nœuds.",
         show="Puis un pilote de chasse de la Navy, en F/A-18, demande à son tour, d'une voix très sûre de lui. 620 nœuds."),
    dict(type='ask', score=(0, 0), img='sr_low',
         say="Alors Walter appuie sur le bouton radio. Los Angeles, ici Aspen vingt. Vous avez notre vitesse sol ?",
         show="Alors Walter appuie sur le bouton radio. « Los Angeles, ici Aspen 20. Vous avez notre vitesse sol ? »"),
    dict(type='radio', score=(0, 0), who="ASPEN 20 · SR-71", img='sr71', kt=1842, n=3,
         say="Un silence. Puis le contrôleur : Aspen vingt, je vous ai à mille huit cent quarante-deux nœuds.",
         show="Un silence. Puis le contrôleur : « Aspen 20, je vous ai à 1 842 nœuds. »"),
    dict(type='punch', score=(0, 0), img='sr_high',
         say="Et Walter répond, tranquillement : Bien reçu. Nous, on l'a à mille huit cent quarante et un.",
         show="Et Walter répond, tranquillement : « Bien reçu. Nous, on l'a à 1 841. »"),
    dict(type='verdict', score=(0, 0),
         say="Plus de trois mille quatre cents kilomètres heure. Après ça, plus personne n'a rien demandé sur la fréquence. Abonne-toi pour d'autres histoires vraies.",
         show="Plus de 3 400 km/h. Après ça, plus personne n'a rien demandé sur la fréquence. Abonne-toi pour d'autres histoires vraies."),
]
END_HOLD = 6.2
