# Biographie : Louis Blériot et la traversée de la Manche (1909)
# scene = type de plan ; say = voix ; show = sous-titres
TITLE = "LOUIS BLÉRIOT"
SCENES = [
    dict(scene='hook',
         say="Vingt-cinq juillet mille neuf cent neuf. Un homme blessé au pied, sans boussole, décolle à l'aube... pour faire ce que personne n'a jamais fait.",
         show="25 juillet 1909. Un homme blessé au pied, sans boussole, décolle à l'aube... pour faire ce que personne n'a jamais fait."),
    dict(scene='portrait',
         say="Il s'appelle Louis Blériot. Trente-sept ans, ingénieur. Il a fait fortune avec des phares de voiture... et il investit tout dans ses machines volantes.",
         show="Il s'appelle Louis Blériot. 37 ans, ingénieur. Il a fait fortune avec des phares de voiture... et il investit tout dans ses machines volantes."),
    dict(scene='journal',
         say="Le défi : un journal anglais, le Daily Mail, promet mille livres au premier qui traversera la Manche en avion.",
         show="Le défi : un journal anglais, le Daily Mail, promet 1 000 livres au premier qui traversera la Manche en avion."),
    dict(scene='rival',
         say="Six jours plus tôt, son rival Hubert Latam a tenté sa chance. Moteur en panne. Il finit à la mer.",
         show="Six jours plus tôt, son rival Hubert Latham a tenté sa chance. Moteur en panne. Il finit à la mer."),
    dict(scene='avion',
         say="Blériot, lui, mise sur le Blériot onze. Du bois, de la toile... et un moteur de seulement vingt-cinq chevaux.",
         show="Blériot, lui, mise sur le Blériot XI. Du bois, de la toile... et un moteur de seulement 25 chevaux."),
    dict(scene='carte',
         say="À l'aube, il décolle des Baraques, près de Calais. Au-dessus de la mer, plus aucun repère. Pendant dix minutes, je suis perdu, racontera-t-il.",
         show="À l'aube, il décolle des Baraques, près de Calais. Au-dessus de la mer, plus aucun repère. « Pendant dix minutes, je suis perdu », racontera-t-il."),
    dict(scene='falaises',
         say="Puis les falaises de Douvres apparaissent. Il se pose brutalement, près du château. Trente-sept minutes de vol. L'exploit est réussi.",
         show="Puis les falaises de Douvres apparaissent. Il se pose brutalement, près du château. 37 minutes de vol. L'exploit est réussi."),
    dict(scene='gloire',
         say="Le monde entier en parle. L'Angleterre n'est plus tout à fait une île. Et Blériot reçoit plus d'une centaine de commandes pour son avion.",
         show="Le monde entier en parle. L'Angleterre n'est plus tout à fait une île. Et Blériot reçoit plus d'une centaine de commandes pour son avion."),
    dict(scene='musee',
         say="Cet avion existe toujours. Il est suspendu au musée des Arts et Métiers, à Paris.",
         show="Cet avion existe toujours. Il est suspendu au musée des Arts et Métiers, à Paris."),
    dict(scene='outro',
         say="Quel pionnier de l'aviation je te raconte ensuite ? Dis-le en commentaire.",
         show="Quel pionnier de l'aviation je te raconte ensuite ? Dis-le en commentaire."),
]
