# Quiz « Reconnais-tu cet avion ? » — say = prononcé, show = affiché
INTRO = dict(say="Dix avions. Trois secondes pour chacun. Si tu les trouves tous, t'es un vrai pilote. Compte tes points !",
             show="10 avions. 3 secondes pour chacun. Si tu les trouves tous, t'es un vrai pilote. Compte tes points !")
OUTRO = dict(say="Alors, combien t'en as eu sur dix ? Écris ton score en commentaire !",
             show="Alors, combien t'en as eu sur 10 ? Écris ton score en commentaire !")

Q = [
    dict(img='concorde', name='Concorde', options=['Tupolev Tu-144', 'Concorde', 'Boeing 2707'], answer=1,
         q_say="Premier avion. Facile pour commencer.", q_show="Premier avion. Facile pour commencer.",
         a_say="C'est le Concorde ! Il reliait Paris à Niou-Yorque en trois heures et demie.",
         a_show="C'est le Concorde ! Il reliait Paris à New York en 3 h 30."),
    dict(img='spitfire', name='Supermarine Spitfire', options=['P-51 Mustang', 'Messerschmitt Bf 109', 'Spitfire'], answer=2,
         q_say="Numéro deux.", q_show="Numéro deux.",
         a_say="Le Spitfaïeur ! La légende de la bataille d'Angleterre, en mille neuf cent quarante.",
         a_show="Le Spitfaïeur ! La légende de la bataille d'Angleterre, en 1940."),
    dict(img='b2', name='Northrop B-2 Spirit', options=['B-2 Spirit', 'B-21 Raider', 'F-117 Nighthawk'], answer=0,
         q_say="Numéro trois. Attention au piège.", q_show="Numéro trois. Attention au piège.",
         a_say="Le bé deux Spirite ! Environ deux milliards de dollars pièce.",
         a_show="Le B-2 Spirit ! Environ 2 milliards de dollars pièce."),
    dict(img='beluga', name='Airbus Beluga', options=['Boeing Dreamlifter', 'Airbus Beluga', 'Super Guppy'], answer=1,
         q_say="Numéro quatre. Celui-là a une drôle de tête.", q_show="Numéro quatre. Celui-là a une drôle de tête.",
         a_say="Le Béluga d'Airbus ! Il transporte des morceaux d'avions entre les usines.",
         a_show="Le Beluga d'Airbus ! Il transporte des morceaux d'avions entre les usines."),
    dict(img='sr71', name='Lockheed SR-71 Blackbird', options=['MiG-25 Foxbat', 'XB-70 Valkyrie', 'SR-71 Blackbird'], answer=2,
         q_say="Numéro cinq.", q_show="Numéro cinq.",
         a_say="Le èss ère soixante et onze Blakbeurde ! Aucun missile ne l'a jamais abattu.",
         a_show="Le SR-71 Blackbird ! Aucun missile ne l'a jamais abattu."),
    dict(img='f22', name='Lockheed Martin F-22 Raptor', options=['F-22 Raptor', 'F-35 Lightning II', 'Su-57'], answer=0,
         q_say="Numéro six. Là, ça se corse.", q_show="Numéro six. Là, ça se corse.",
         a_say="Le F vingt-deux Raptor ! Il vole en supersonique sans postcombustion.",
         a_show="Le F-22 Raptor ! Il vole en supersonique sans postcombustion."),
    dict(img='a10', name='Fairchild A-10 Thunderbolt II', options=['Soukhoï Su-25', 'A-10 Thunderbolt II', 'A-4 Skyhawk'], answer=1,
         q_say="Numéro sept.", q_show="Numéro sept.",
         a_say="Le A dix Ouortogue ! Un avion construit autour de son énorme canon de trente millimètres.",
         a_show="Le A-10 « Warthog » ! Un avion construit autour de son énorme canon de 30 mm."),
    dict(img='m2000', name='Dassault Mirage 2000', options=['Rafale', 'Gripen', 'Mirage 2000'], answer=2,
         q_say="Numéro huit. Pour les Français.", q_show="Numéro huit. Pour les Français.",
         a_say="Le Mirage deux mille ! En service dans l'armée de l'Air depuis mille neuf cent quatre-vingt-quatre.",
         a_show="Le Mirage 2000 ! En service dans l'armée de l'Air depuis 1984."),
    dict(img='f117', name='Lockheed F-117 Nighthawk', options=['YF-23', 'F-117 Nighthawk', 'B-2 Spirit'], answer=1,
         q_say="Numéro neuf. Presque fini.", q_show="Numéro neuf. Presque fini.",
         a_say="Le F cent dix-sept Naille-toque ! Le premier avion furtif opérationnel de l'histoire.",
         a_show="Le F-117 Nighthawk ! Le premier avion furtif opérationnel de l'histoire."),
    dict(img='an225', name='Antonov An-225 Mriya', options=['Antonov An-124', 'Lockheed C-5 Galaxy', 'Antonov An-225'], answer=2,
         q_say="Dernier avion. Le plus dur. Regarde bien...", q_show="Dernier avion. Le plus dur. Regarde bien...",
         a_say="L'Antonov deux cent vingt-cinq ! Le plus gros avion du monde, détruit en deux mille vingt-deux.",
         a_show="L'Antonov An-225 ! Le plus gros avion du monde, détruit en 2022."),
]
