# Quiz #3 — avions de légende (histoire)
INTRO = dict(say="Quiz avions de légende ! Dix machines qui ont écrit l'histoire. Trois secondes chacune. Compte tes points !",
             show="Quiz avions de légende ! 10 machines qui ont écrit l'histoire. 3 secondes chacune. Compte tes points !")
OUTRO = dict(say="Alors, combien sur dix ? Écris ton score en commentaire, et dis-moi quelle légende je dois te raconter !",
             show="Alors, combien sur 10 ? Écris ton score en commentaire, et dis-moi quelle légende je dois te raconter !")
Q = [
    dict(img='wright', name='Wright Flyer', options=['Wright Flyer', 'Éole de Clément Ader', 'Demoiselle'], answer=0,
         q_say="Premier avion. Le plus vieux de tous.", q_show="Premier avion. Le plus vieux de tous.",
         a_say="Le Flyer des frères Wright ! Premier vol motorisé contrôlé, en mille neuf cent trois. Il a duré douze secondes.",
         a_show="Le Flyer des frères Wright ! Premier vol motorisé contrôlé, en 1903. Il a duré 12 secondes."),
    dict(img='dr1', name='Fokker Dr.I', options=['Sopwith Triplane', 'Fokker Dr.I', 'Albatros D.V'], answer=1,
         q_say="Numéro deux. Compte ses ailes.", q_show="Numéro deux. Compte ses ailes.",
         a_say="Le Fokker triplan ! L'avion rouge du Baron rouge, Manfred von Richthofen.",
         a_show="Le Fokker Dr.I ! L'avion rouge du Baron rouge, Manfred von Richthofen."),
    dict(img='spad', name='SPAD VII', options=['Nieuport 17', 'Sopwith Pup', 'SPAD VII'], answer=2,
         q_say="Numéro trois. Un avion français.", q_show="Numéro trois. Un avion français.",
         a_say="Le SPAD sept ! Le chasseur de l'as français Georges Guinemère.",
         a_show="Le SPAD VII ! Le chasseur de l'as français Georges Guynemer."),
    dict(img='x1', name='Bell X-1', options=['Bell X-1', 'X-15', 'Douglas Skyrocket'], answer=0,
         q_say="Numéro quatre. Il a fait du bruit.", q_show="Numéro quatre. Il a fait du bruit.",
         a_say="Le Bell X un ! Premier avion à passer le mur du son en palier, avec Chuck Yeager, en mille neuf cent quarante-sept.",
         a_show="Le Bell X-1 ! Premier avion à passer le mur du son en palier, avec Chuck Yeager, en 1947."),
    dict(img='vega', name='Lockheed Vega', options=['Ryan NYP', 'Lockheed Vega', 'Stinson Detroiter'], answer=1,
         q_say="Numéro cinq. Indice : une aviatrice célèbre.", q_show="Numéro cinq. Indice : une aviatrice célèbre.",
         a_say="Le Lockheed Vega ! Amelia Earhart a traversé l'Atlantique seule à son bord, en mille neuf cent trente-deux.",
         a_show="Le Lockheed Vega ! Amelia Earhart a traversé l'Atlantique seule à son bord, en 1932."),
    dict(img='camel', name='Sopwith Camel', options=['SPAD XIII', 'Sopwith Camel', 'Bristol F.2'], answer=1,
         q_say="Numéro six.", q_show="Numéro six.",
         a_say="Le Sopwith Camel ! Le chasseur allié le plus victorieux de la Première Guerre mondiale.",
         a_show="Le Sopwith Camel ! Le chasseur allié le plus victorieux de la Première Guerre mondiale."),
    dict(img='mirage3', name='Dassault Mirage III', options=['Mirage 2000', 'Mirage III', 'Mirage F1'], answer=1,
         q_say="Numéro sept. Piège pour les Français.", q_show="Numéro sept. Piège pour les Français.",
         a_say="Le Mirage trois ! Le premier avion européen à dépasser Mach deux en palier.",
         a_show="Le Mirage III ! Le premier avion européen à dépasser Mach 2 en palier."),
    dict(img='morane', name='Morane-Saulnier L', options=['Morane-Saulnier L', 'Blériot XI', 'Fokker Eindecker'], answer=0,
         q_say="Numéro huit. Celui-là est dur.", q_show="Numéro huit. Celui-là est dur.",
         a_say="Le Morane-Saulnier L ! Roland Garros y a fixé des déflecteurs pour tirer à travers l'hélice.",
         a_show="Le Morane-Saulnier L ! Roland Garros y a fixé des déflecteurs pour tirer à travers l'hélice."),
    dict(img='zero', name='Mitsubishi A6M Zero', options=['Mitsubishi Zero', 'Nakajima Hayabusa', 'Kawasaki Hien'], answer=0,
         q_say="Numéro neuf.", q_show="Numéro neuf.",
         a_say="Le Mitsubishi Zéro ! Le chasseur japonais le plus célèbre de la Seconde Guerre mondiale.",
         a_show="Le Mitsubishi Zero ! Le chasseur japonais le plus célèbre de la Seconde Guerre mondiale."),
    dict(img='x15', name='North American X-15', options=['SR-71', 'X-15', 'Bell X-2'], answer=1,
         q_say="Dernier. Le plus fou.", q_show="Dernier. Le plus fou.",
         a_say="Le X quinze ! Un avion-fusée à Mach six virgule sept. Le record de vitesse d'un avion piloté.",
         a_show="Le X-15 ! Un avion-fusée à Mach 6,7. Le record de vitesse d'un avion piloté."),
]
