# Quiz #2 — « niveau pilote »
INTRO = dict(say="Quiz niveau pilote ! Dix avions, trois secondes chacun. Les avions de ligne vont te piéger. Compte tes points !",
             show="Quiz niveau pilote ! 10 avions, 3 secondes chacun. Les avions de ligne vont te piéger. Compte tes points !")
OUTRO = dict(say="Alors, combien sur dix ? Si t'as tout bon, t'es prêt pour le cockpit. Écris ton score en commentaire !",
             show="Alors, combien sur 10 ? Si t'as tout bon, t'es prêt pour le cockpit. Écris ton score en commentaire !")
Q = [
    dict(img='alphajet', name='Dassault Alpha Jet', options=['Alpha Jet', 'Hawk', 'L-39 Albatros'], answer=0,
         q_say="Premier avion. Les Français devraient le trouver.", q_show="Premier avion. Les Français devraient le trouver.",
         a_say="L'Alpha Jet ! L'avion de la Patrouille de France.",
         a_show="L'Alpha Jet ! L'avion de la Patrouille de France."),
    dict(img='f16', name='General Dynamics F-16', options=['F-15 Eagle', 'Gripen', 'F-16 Falcon'], answer=2,
         q_say="Numéro deux.", q_show="Numéro deux.",
         a_say="Le F seize ! Plus de quatre mille cinq cents exemplaires construits.",
         a_show="Le F-16 ! Plus de 4 500 exemplaires construits."),
    dict(img='a330', name='Airbus A330', options=['Boeing 777', 'Airbus A330', 'Airbus A350'], answer=1,
         q_say="Numéro trois. Premier avion de ligne...", q_show="Numéro trois. Premier avion de ligne...",
         a_say="L'Airbus A trois cent trente ! Un long-courrier biréacteur.",
         a_show="L'Airbus A330 ! Un long-courrier biréacteur."),
    dict(img='caravelle', name='Sud Aviation Caravelle', options=['Caravelle', 'Comet', 'Tupolev Tu-134'], answer=0,
         q_say="Numéro quatre. Un indice : il est français.", q_show="Numéro quatre. Un indice : il est français.",
         a_say="La Caravelle ! Ses moteurs étaient à l'arrière, une première pour un avion de ligne.",
         a_show="La Caravelle ! Ses moteurs étaient à l'arrière, une première pour un avion de ligne."),
    dict(img='c130', name='Lockheed C-130 Hercules', options=['A400M Atlas', 'C-130 Hercules', 'Transall C-160'], answer=1,
         q_say="Numéro cinq.", q_show="Numéro cinq.",
         a_say="Le cé cent trente Hercule ! Produit depuis les années cinquante, et toujours fabriqué.",
         a_show="Le C-130 Hercules ! Produit depuis les années 1950, et toujours fabriqué."),
    dict(img='b787', name='Boeing 787 Dreamliner', options=['Boeing 787', 'Airbus A350', 'Boeing 767'], answer=0,
         q_say="Numéro six. Attention, piège.", q_show="Numéro six. Attention, piège.",
         a_say="Le Bo-inng sept cent quatre-vingt-sept ! Son fuselage est en grande partie en matériaux composites.",
         a_show="Le Boeing 787 ! Son fuselage est en grande partie en matériaux composites."),
    dict(img='su37', name='Soukhoï Su-37', options=['F-15 Eagle', 'Soukhoï Su-37', 'MiG-29'], answer=1,
         q_say="Numéro sept. Celui-là est rare.", q_show="Numéro sept. Celui-là est rare.",
         a_say="Le Soukhoï trente-sept ! Un prototype russe ultra maniable, jamais produit en série.",
         a_show="Le Soukhoï Su-37 ! Un prototype russe ultra maniable, jamais produit en série."),
    dict(img='a320', name='Airbus A320', options=['Boeing 737', 'Airbus A320', 'Airbus A220'], answer=1,
         q_say="Numéro huit. Tu l'as sûrement déjà pris.", q_show="Numéro huit. Tu l'as sûrement déjà pris.",
         a_say="L'Airbus A trois cent vingt ! Le best-seller d'Airbus.",
         a_show="L'Airbus A320 ! Le best-seller d'Airbus."),
    dict(img='b52', name='Boeing B-52 Stratofortress', options=['B-52 Stratofortress', 'Tu-95 Bear', 'B-1 Lancer'], answer=0,
         q_say="Numéro neuf. Compte ses moteurs.", q_show="Numéro neuf. Compte ses moteurs.",
         a_say="Le bé cinquante-deux ! Huit moteurs, et en service depuis plus de soixante-dix ans.",
         a_show="Le B-52 ! 8 moteurs, et en service depuis plus de 70 ans."),
    dict(img='b767', name='Boeing 767', options=['Airbus A300', 'Boeing 757', 'Boeing 767'], answer=2,
         q_say="Dernier. Le plus dur. Regarde bien le fuselage...", q_show="Dernier. Le plus dur. Regarde bien le fuselage...",
         a_say="Le Bo-inng sept cent soixante-sept ! Plus large que le sept cent cinquante-sept, il a deux couloirs.",
         a_show="Le Boeing 767 ! Plus large que le 757, il a deux couloirs."),
]
