# Quiz #4 — avions de chasse modernes (silhouettes)
INTRO = dict(say="Quiz silhouettes, spécial avions de combat ! Dix avions, trois secondes chacun. Le dernier piège tout le monde.",
             show="Quiz silhouettes, spécial avions de combat ! 10 avions, 3 secondes chacun. Le dernier piège tout le monde.")
OUTRO = dict(say="Alors, combien sur dix ? Écris ton score en commentaire !",
             show="Alors, combien sur 10 ? Écris ton score en commentaire !")
Q = [
    dict(img='f117', name='F-117 Nighthawk', options=['B-2 Spirit', 'F-117 Nighthawk', 'F-22 Raptor'], answer=1,
         q_say="Numéro un. Tout en angles.", q_show="Numéro un. Tout en angles.",
         a_say="Le F cent dix-sept ! Le premier avion furtif opérationnel. Il est resté secret jusqu'en mille neuf cent quatre-vingt-huit.",
         a_show="Le F-117 ! Le premier avion furtif opérationnel. Il est resté secret jusqu'en 1988."),
    dict(img='a10', name='A-10 Thunderbolt II', options=['A-10 Thunderbolt II', 'Su-25', 'Jaguar'], answer=0,
         q_say="Numéro deux. Regarde les moteurs.", q_show="Numéro deux. Regarde les moteurs.",
         a_say="Le A dix ! Surnommé le phacochère, il est construit autour d'un énorme canon de trente millimètres.",
         a_show="Le A-10 ! Surnommé « Warthog », il est construit autour d'un énorme canon de 30 mm."),
    dict(img='m2000', name='Mirage 2000', options=['Rafale', 'Mirage III', 'Mirage 2000'], answer=2,
         q_say="Numéro trois. Un français.", q_show="Numéro trois. Un français.",
         a_say="Le Mirage deux mille ! Aile delta, un seul moteur, et toujours en service dans l'armée de l'Air.",
         a_show="Le Mirage 2000 ! Aile delta, un seul moteur, et toujours en service dans l'armée de l'Air."),
    dict(img='harrier', name='Harrier', options=['Harrier', 'F-35B', 'Yak-38'], answer=0,
         q_say="Numéro quatre. Il n'a pas besoin de piste.", q_show="Numéro quatre. Il n'a pas besoin de piste.",
         a_say="Le Harrier ! Le premier chasseur opérationnel capable de décoller et d'atterrir à la verticale.",
         a_show="Le Harrier ! Le premier chasseur opérationnel capable de décoller et d'atterrir à la verticale."),
    dict(img='f15', name='F-15 Eagle', options=['MiG-29', 'F-15 Eagle', 'F-14 Tomcat'], answer=1,
         q_say="Numéro cinq. Deux dérives.", q_show="Numéro cinq. Deux dérives.",
         a_say="Le F quinze ! Plus de cent victoires en combat aérien, et aucune défaite.",
         a_show="Le F-15 ! Plus de 100 victoires en combat aérien, et aucune défaite."),
    dict(img='typhoon', name='Eurofighter Typhoon', options=['Rafale', 'Gripen', 'Eurofighter Typhoon'], answer=2,
         q_say="Numéro six. Attention au piège.", q_show="Numéro six. Attention au piège.",
         a_say="Le Typhoon ! Construit par quatre pays : Royaume-Uni, Allemagne, Italie et Espagne.",
         a_show="Le Typhoon ! Construit par 4 pays : Royaume-Uni, Allemagne, Italie et Espagne."),
    dict(img='sr71', name='SR-71 Blackbird', options=['SR-71 Blackbird', 'XB-70 Valkyrie', 'MiG-25'], answer=0,
         q_say="Numéro sept. Le plus rapide.", q_show="Numéro sept. Le plus rapide.",
         a_say="Le S R soixante et onze ! Plus de Mach trois. Son record de vitesse tient depuis mille neuf cent soixante-seize.",
         a_show="Le SR-71 ! Plus de Mach 3. Son record de vitesse tient depuis 1976."),
    dict(img='su37', name='Soukhoï Su-37', options=['F-15', 'MiG-29', 'Soukhoï Su-37'], answer=2,
         q_say="Numéro huit. Celui-là est dur.", q_show="Numéro huit. Celui-là est dur.",
         a_say="Le Soukhoï Su trente-sept ! Un prototype russe à poussée vectorielle, construit en un seul exemplaire.",
         a_show="Le Soukhoï Su-37 ! Un prototype russe à poussée vectorielle, construit en un seul exemplaire."),
    dict(img='f35', name='F-35 Lightning II', options=['F-22 Raptor', 'F-35 Lightning II', 'J-31'], answer=1,
         q_say="Numéro neuf. Un seul moteur.", q_show="Numéro neuf. Un seul moteur.",
         a_say="Le F trente-cinq ! Le chasseur le plus produit de sa génération : plus de mille exemplaires livrés.",
         a_show="Le F-35 ! Le chasseur le plus produit de sa génération : plus de 1 000 exemplaires livrés."),
    dict(img='f22', name='F-22 Raptor', options=['F-35', 'Su-57', 'F-22 Raptor'], answer=2,
         q_say="Dernier. Ne confonds pas.", q_show="Dernier. Ne confonds pas.",
         a_say="Le F vingt-deux ! Les États-Unis interdisent de le vendre, même à leurs alliés.",
         a_show="Le F-22 ! Les États-Unis interdisent de l'exporter, même à leurs alliés."),
]
