# Quiz #6 — silhouettes : spécial France
# Faits : Blériot XI Manche 25/07/1909 ; SPAD VII de Guynemer ; Morane-Saulnier L + déflecteurs de Roland Garros (1915) ; Caravelle 1er vol 27/05/1955 ;
# Mirage III premier avion européen à Mach 2 en palier ; Concorde assemblé à Toulouse et Filton ; Alpha Jet = Patrouille de France ;
# Mirage 2000 commandes de vol électriques ; A320 famille la plus commandée ; Rafale A 1er vol 04/07/1986
INTRO = dict(say="Quiz silhouettes, spécial France ! Dix avions français, trois secondes chacun. Le dernier piège tout le monde.",
             show="Quiz silhouettes : spécial France ! 10 avions, 3 secondes chacun.")
OUTRO = dict(say="Alors, combien sur dix ? Écris ton score en commentaire !",
             show="Alors, combien sur 10 ? Écris ton score en commentaire !")
Q = [
    dict(img='bleriot_a', name='Blériot XI', options=['Blériot XI', 'Demoiselle', 'Antoinette'], answer=0,
         q_say="Numéro un. Le plus vieux.", q_show="Numéro un. Le plus vieux.",
         a_say="Le Blériot onze ! Le premier avion à traverser la Manche, en mille neuf cent neuf.",
         a_show="Le Blériot XI ! Le premier avion à traverser la Manche, en 1909."),
    dict(img='spad', name='SPAD VII', options=['Nieuport 17', 'SPAD VII', 'Sopwith Camel'], answer=1,
         q_say="Numéro deux. Un chasseur de quatorze-dix-huit.", q_show="Numéro deux. Un chasseur de 14-18.",
         a_say="Le SPAD sept ! Le chasseur de l'as français Georges Guinemère.",
         a_show="Le SPAD VII ! Le chasseur de l'as français Georges Guynemer."),
    dict(img='morane', name='Morane-Saulnier L', options=['Fokker Eindecker', 'Blériot XI', 'Morane-Saulnier L'], answer=2,
         q_say="Numéro trois. Celui-là est dur.", q_show="Numéro trois. Celui-là est dur.",
         a_say="Le Morane-Saulnier L ! Roland Garros y a monté une mitrailleuse qui tirait à travers l'hélice.",
         a_show="Le Morane-Saulnier L ! Roland Garros y a monté une mitrailleuse qui tirait à travers l'hélice."),
    dict(img='caravelle', name='Caravelle', options=['Caravelle', 'De Havilland Comet', 'Hawker Trident'], answer=0,
         q_say="Numéro quatre. Un avion de ligne.", q_show="Numéro quatre. Un avion de ligne.",
         a_say="La Caravelle ! Le premier avion de ligne à réaction français. Premier vol en mille neuf cent cinquante-cinq.",
         a_show="La Caravelle ! Le premier avion de ligne à réaction français. Premier vol en 1955."),
    dict(img='mirage3', name='Mirage III', options=['Mirage F1', 'Mirage 5', 'Mirage III'], answer=2,
         q_say="Numéro cinq. Une aile en triangle.", q_show="Numéro cinq. Une aile en triangle.",
         a_say="Le Mirage trois ! Le premier avion européen à dépasser Mach deux en palier.",
         a_show="Le Mirage III ! Le premier avion européen à dépasser Mach 2 en palier."),
    dict(img='concorde', name='Concorde', options=['Concorde', 'Tupolev Tu-144', 'Boeing 2707'], answer=0,
         q_say="Numéro six. Trop facile ?", q_show="Numéro six. Trop facile ?",
         a_say="Le Concorde ! Franco-britannique, assemblé à Toulouse et en Angleterre.",
         a_show="Le Concorde ! Franco-britannique, assemblé à Toulouse et à Filton."),
    dict(img='alphajet', name='Alpha Jet', options=['BAE Hawk', 'Alpha Jet', 'Aermacchi MB-339'], answer=1,
         q_say="Numéro sept. Tu l'as déjà vu le quatorze juillet.", q_show="Numéro sept. Tu l'as déjà vu le 14 juillet.",
         a_say="L'Alpha Jet ! L'avion de la Patrouille de France.",
         a_show="L'Alpha Jet ! L'avion de la Patrouille de France."),
    dict(img='m2000', name='Mirage 2000', options=['Mirage 2000', 'Mirage III', 'Rafale'], answer=0,
         q_say="Numéro huit. Attention au piège.", q_show="Numéro huit. Attention au piège.",
         a_say="Le Mirage deux mille ! Un seul moteur, une aile delta et des commandes de vol électriques.",
         a_show="Le Mirage 2000 ! Un seul moteur, une aile delta et des commandes de vol électriques."),
    dict(img='a320', name='Airbus A320', options=['Boeing 737', 'Airbus A220', 'Airbus A320'], answer=2,
         q_say="Numéro neuf. Assemblé à Toulouse.", q_show="Numéro neuf. Assemblé à Toulouse.",
         a_say="L'Airbus A trois cent vingt ! La famille d'avions de ligne la plus commandée au monde.",
         a_show="L'Airbus A320 ! La famille d'avions de ligne la plus commandée au monde."),
    dict(img='rafale', name='Rafale', options=['Eurofighter Typhoon', 'Rafale', 'Saab Gripen'], answer=1,
         q_say="Dernier. Ne te trompe pas.", q_show="Dernier. Ne te trompe pas.",
         a_say="Le Rafale ! Son premier prototype a volé en mille neuf cent quatre-vingt-six.",
         a_show="Le Rafale ! Son premier prototype a volé en 1986."),
]
