# Quiz #5 — silhouettes : avions de ligne et cargos
# Faits : 747 1er vol 09/02/1969 ; A320 1er avion de ligne à commandes de vol électriques numériques ; Beluga transporte des sections d'Airbus ;
# 787 ~50 % composites (masse) ; Caravelle réacteurs arrière (1er vol 1955) ; An-225 conçu pour Bourane ; A330/A340 même aile et cockpit ;
# Concorde New York-Londres 2 h 52 min 59 s (07/02/1996) ; A400M hélices contrarotatives par paires ; KC-46 = base 767
INTRO = dict(say="Quiz silhouettes, avions de ligne et cargos ! Dix avions, trois secondes chacun. Le dernier piège tout le monde.",
             show="Quiz silhouettes : avions de ligne et cargos ! 10 avions, 3 secondes chacun.")
OUTRO = dict(say="Alors, combien sur dix ? Écris ton score en commentaire !",
             show="Alors, combien sur 10 ? Écris ton score en commentaire !")
Q = [
    dict(img='vc25', name='Boeing 747', options=['Airbus A380', 'Boeing 747', 'Boeing 777'], answer=1,
         q_say="Numéro un. Regarde la bosse.", q_show="Numéro un. Regarde la bosse.",
         a_say="Le Boeing sept cent quarante-sept ! Le premier gros-porteur de l'histoire. Premier vol en mille neuf cent soixante-neuf.",
         a_show="Le Boeing 747 ! Le premier gros-porteur de l'histoire. Premier vol en 1969."),
    dict(img='a320', name='Airbus A320', options=['Boeing 737', 'Airbus A220', 'Airbus A320'], answer=2,
         q_say="Numéro deux. Tu l'as sûrement déjà pris.", q_show="Numéro deux. Tu l'as sûrement déjà pris.",
         a_say="L'Airbus A trois cent vingt ! Le premier avion de ligne à commandes de vol électriques numériques.",
         a_show="L'Airbus A320 ! Le premier avion de ligne à commandes de vol électriques numériques."),
    dict(img='beluga', name='Airbus Beluga', options=['Super Guppy', 'Airbus Beluga', 'Dreamlifter'], answer=1,
         q_say="Numéro trois. Une drôle de tête.", q_show="Numéro trois. Une drôle de tête.",
         a_say="Le Beluga ! Il transporte des morceaux d'Airbus entre les usines européennes.",
         a_show="Le Beluga ! Il transporte des morceaux d'Airbus entre les usines européennes."),
    dict(img='b787', name='Boeing 787', options=['Boeing 787', 'Airbus A350', 'Boeing 777'], answer=0,
         q_say="Numéro quatre. Regarde ses ailes.", q_show="Numéro quatre. Regarde ses ailes.",
         a_say="Le Boeing sept cent quatre-vingt-sept ! La moitié de sa structure est en matériaux composites.",
         a_show="Le Boeing 787 ! La moitié de sa structure est en matériaux composites."),
    dict(img='caravelle', name='Sud Aviation Caravelle', options=['Caravelle', 'De Havilland Comet', 'DC-9'], answer=0,
         q_say="Numéro cinq. Un français.", q_show="Numéro cinq. Un français.",
         a_say="La Caravelle ! Le premier avion de ligne avec ses réacteurs à l'arrière.",
         a_show="La Caravelle ! Le premier avion de ligne avec ses réacteurs à l'arrière."),
    dict(img='an225', name='Antonov An-225', options=['C-5 Galaxy', 'Antonov An-124', 'Antonov An-225'], answer=2,
         q_say="Numéro six. Compte les moteurs.", q_show="Numéro six. Compte les moteurs.",
         a_say="L'Antonov deux cent vingt-cinq ! Il a été conçu pour porter la navette spatiale soviétique sur son dos.",
         a_show="L'Antonov An-225 ! Il a été conçu pour porter la navette spatiale soviétique Bourane sur son dos."),
    dict(img='a330', name='Airbus A330', options=['Boeing 767', 'Airbus A330', 'Boeing 777'], answer=1,
         q_say="Numéro sept. Attention au piège.", q_show="Numéro sept. Attention au piège.",
         a_say="L'Airbus A trois cent trente ! Il a la même aile et le même cockpit que le quadrimoteur A trois cent quarante.",
         a_show="L'Airbus A330 ! Il a la même aile et le même cockpit que le quadrimoteur A340."),
    dict(img='concorde', name='Concorde', options=['Tupolev Tu-144', 'Concorde', 'Boeing 2707'], answer=1,
         q_say="Numéro huit. Il allait très vite.", q_show="Numéro huit. Il allait très vite.",
         a_say="Le Concorde ! Son record : New York-Londres en deux heures cinquante-trois.",
         a_show="Le Concorde ! Son record : New York-Londres en 2 h 53."),
    dict(img='a400m', name='Airbus A400M', options=['C-130 Hercules', 'Airbus A400M', 'Transall C-160'], answer=1,
         q_say="Numéro neuf. Un militaire européen.", q_show="Numéro neuf. Un militaire européen.",
         a_say="L'Airbus A quatre cents M ! Ses hélices tournent par paires, en sens opposés.",
         a_show="L'Airbus A400M ! Ses hélices tournent par paires, en sens opposés."),
    dict(img='b767', name='Boeing 767', options=['Airbus A330', 'Boeing 767', 'Boeing 787'], answer=1,
         q_say="Dernier. Ne le confonds pas avec le numéro sept.", q_show="Dernier. Ne le confonds pas avec le numéro sept.",
         a_say="Le Boeing sept cent soixante-sept ! L'armée américaine en a fait un avion ravitailleur.",
         a_show="Le Boeing 767 ! L'armée américaine en a fait un avion ravitailleur, le KC-46."),
]
