INTRO = dict(say="Vrai ou faux ? Huit idées reçues sur les avions de ligne. Trois secondes pour répondre. La quatrième va te surprendre !",
             show="Vrai ou faux ? 8 idées reçues sur les avions de ligne. 3 secondes pour répondre.")
OUTRO = dict(say="Alors, combien t'en as eu sur huit ? Écris ton score en commentaire !",
             show="Alors, combien t'en as eu sur 8 ? Écris ton score en commentaire !")
Q = [
    dict(img='a320', stmt="On peut ouvrir une porte d'avion en plein vol.", answer=1,
         q_say="Numéro un. On peut ouvrir une porte d'avion en plein vol.",
         a_say="Faux ! La pression de la cabine plaque la porte contre l'avion avec plusieurs tonnes de force.",
         a_show="Faux ! La pression de la cabine plaque la porte contre l'avion avec plusieurs tonnes de force."),
    dict(img='b787', stmt="Les hublots ont un petit trou fait exprès.", answer=0,
         q_say="Numéro deux. Les hublots ont un petit trou fait exprès.",
         a_say="Vrai ! Il équilibre la pression entre les vitres, pour que la vitre extérieure encaisse seule l'effort.",
         a_show="Vrai ! Il équilibre la pression entre les vitres, pour que la vitre extérieure encaisse seule l'effort."),
    dict(img='a330', stmt="Un avion de ligne est frappé par la foudre environ une fois par an.", answer=0,
         q_say="Numéro trois. Un avion de ligne est frappé par la foudre environ une fois par an.",
         a_say="Vrai ! Et il est conçu pour : le courant glisse sur la carlingue et ressort par l'arrière.",
         a_show="Vrai ! Et il est conçu pour : le courant glisse sur la carlingue et ressort par l'arrière."),
    dict(img='b767', stmt="Un biréacteur peut continuer à voler avec un seul moteur.", answer=0,
         q_say="Numéro quatre. Un biréacteur peut continuer à voler avec un seul moteur.",
         a_say="Vrai ! Il est certifié pour, et peut rejoindre un aéroport de déroutement en toute sécurité.",
         a_show="Vrai ! Il est certifié pour, et peut rejoindre un aéroport de déroutement en toute sécurité."),
    dict(img='a320', stmt="Il faut gonfler son gilet de sauvetage avant de sortir de l'avion.", answer=1,
         q_say="Numéro cinq. Il faut gonfler son gilet de sauvetage avant de sortir de l'avion.",
         a_say="Faux ! On le gonfle à la porte. Gonflé dans la cabine, il peut te bloquer si l'eau entre.",
         a_show="Faux ! On le gonfle à la porte. Gonflé dans la cabine, il peut te bloquer si l'eau entre."),
    dict(img='caravelle', stmt="Le commandant et le copilote mangent souvent des repas différents.", answer=0,
         q_say="Numéro six. Le commandant et le copilote mangent souvent des repas différents.",
         a_say="Vrai ! Beaucoup de compagnies l'imposent : une intoxication ne doit jamais toucher les deux pilotes.",
         a_show="Vrai ! Beaucoup de compagnies l'imposent : une intoxication ne doit jamais toucher les deux pilotes."),
    dict(img='a330', stmt="Les masques à oxygène fonctionnent pendant des heures.", answer=1,
         q_say="Numéro sept. Les masques à oxygène fonctionnent pendant des heures.",
         a_say="Faux ! Environ un quart d'heure : le temps que les pilotes descendent à une altitude où l'on respire.",
         a_show="Faux ! Environ un quart d'heure : le temps que les pilotes descendent à une altitude où l'on respire."),
    dict(img='concorde', stmt="Le Concorde volait plus haut que les avions de ligne d'aujourd'hui.", answer=0,
         q_say="Dernière. Le Concorde volait plus haut que les avions de ligne actuels.",
         a_say="Vrai ! Jusqu'à dix-huit mille mètres, contre environ douze mille pour un avion de ligne moderne.",
         a_show="Vrai ! Jusqu'à 18 000 mètres, contre environ 12 000 pour un avion de ligne moderne."),
]
