# Vrai ou faux : spécial aviation française (faits vérifiés : Rafale M / Charles de Gaulle ; Patrouille de France = Alpha Jet ; Mirage 2000 1er vol 10/03/1978 ;
# Concorde franco-britannique ; Blériot 25/07/1909 ~36 min ; Charles de Gaulle seul porte-avions nucléaire hors US Navy ; Caravelle 1er vol 1955 ; Rafale Mach 1,8)
INTRO = dict(say="Vrai ou faux, spécial aviation française ! Huit affirmations, trois secondes pour répondre. La dernière piège tout le monde.",
             show="Vrai ou faux : spécial aviation française ! 8 affirmations, 3 secondes pour répondre.")
OUTRO = dict(say="Alors, combien sur huit ? Écris ton score en commentaire !",
             show="Alors, combien sur 8 ? Écris ton score en commentaire !")
Q = [
    dict(img='rafale', stmt="Le Rafale peut se poser sur un porte-avions.", answer=0,
         q_say="Numéro un. Le Rafale peut se poser sur un porte-avions.",
         a_say="Vrai ! Le Rafale Marine se pose sur le Charles de Gaulle, arrêté par un câble.",
         a_show="Vrai ! Le Rafale Marine se pose sur le Charles-de-Gaulle, arrêté par un câble."),
    dict(img='alphajet', stmt="La Patrouille de France vole sur Rafale.", answer=1,
         q_say="Numéro deux. La Patrouille de France vole sur Rafale.",
         a_say="Faux ! Elle vole sur Alpha Jet, un avion d'entraînement.",
         a_show="Faux ! Elle vole sur Alpha Jet, un avion d'entraînement."),
    dict(img='m2000', stmt="Le Mirage 2000 a volé pour la première fois en 1978.", answer=0,
         q_say="Numéro trois. Le Mirage deux mille a volé pour la première fois en mille neuf cent soixante-dix-huit.",
         a_say="Vrai ! Premier vol en mars mille neuf cent soixante-dix-huit.",
         a_show="Vrai ! Premier vol en mars 1978."),
    dict(img='concorde', stmt="Le Concorde était un avion 100 % français.", answer=1,
         q_say="Numéro quatre. Le Concorde était un avion cent pour cent français.",
         a_say="Faux ! C'était un programme franco-britannique.",
         a_show="Faux ! C'était un programme franco-britannique."),
    dict(img='bleriot_a', stmt="Blériot a traversé la Manche en moins de 40 minutes.", answer=0,
         q_say="Numéro cinq. Blériot a traversé la Manche en moins de quarante minutes.",
         a_say="Vrai ! Environ trente-six minutes, en mille neuf cent neuf.",
         a_show="Vrai ! Environ 36 minutes, en 1909."),
    dict(img='rafale', stmt="Le Charles de Gaulle est le seul porte-avions nucléaire hors des États-Unis.", answer=0,
         q_say="Numéro six. Le Charles de Gaulle est le seul porte-avions nucléaire hors des États-Unis.",
         a_say="Vrai ! Aucun autre pays n'en a.",
         a_show="Vrai ! Aucun autre pays n'en a."),
    dict(img='caravelle', stmt="La Caravelle était un avion de ligne à réaction français.", answer=0,
         q_say="Numéro sept. La Caravelle était un avion de ligne à réaction français.",
         a_say="Vrai ! Premier vol en mille neuf cent cinquante-cinq.",
         a_show="Vrai ! Premier vol en 1955."),
    dict(img='rafale', stmt="Le Rafale vole à Mach 2.", answer=1,
         q_say="Dernière. Le Rafale vole à Mach deux.",
         a_say="Faux ! Mach un virgule huit. Pas tout à fait deux.",
         a_show="Faux ! Mach 1,8. Pas tout à fait 2."),
]
