# Vrai ou faux aviation — say = prononcé, show = affiché
INTRO = dict(say="Vrai ou faux ? Huit affirmations sur des avions légendaires. Trois secondes pour répondre. Compte tes points !",
             show="Vrai ou faux ? 8 affirmations sur des avions légendaires. 3 secondes pour répondre. Compte tes points !")
OUTRO = dict(say="Alors, combien t'en as eu sur huit ? Écris ton score en commentaire !",
             show="Alors, combien t'en as eu sur 8 ? Écris ton score en commentaire !")

Q = [
    dict(img='concorde', stmt="Le Concorde reliait Paris à New York en moins de 4 heures.", answer=0,
         q_say="Numéro un. Le Concorde reliait Paris à Niou-Yorque en moins de quatre heures.",
         a_say="Vrai ! Environ trois heures et demie, deux fois plus vite qu'un avion de ligne classique.",
         a_show="Vrai ! Environ 3 h 30, deux fois plus vite qu'un avion de ligne classique."),
    dict(img='b2', stmt="Le bombardier B-2 possède une dérive verticale.", answer=1,
         q_say="Numéro deux. Le bombardier bé deux possède une dérive verticale.",
         a_say="Faux ! C'est une aile volante : pas de dérive, ce qui le rend plus furtif.",
         a_show="Faux ! C'est une aile volante : pas de dérive, ce qui le rend plus furtif."),
    dict(img='sr71', stmt="Le SR-71 s'allongeait en vol à cause de la chaleur.", answer=0,
         q_say="Numéro trois. Le èss ère soixante et onze s'allongeait en vol à cause de la chaleur.",
         a_say="Vrai ! À Mach trois, la friction de l'air chauffait tellement son titane qu'il se dilatait de plusieurs centimètres.",
         a_show="Vrai ! À Mach 3, la friction de l'air chauffait son titane au point qu'il se dilatait de plusieurs centimètres."),
    dict(img='f117', stmt="Le F-117 furtif n'a jamais été abattu.", answer=1,
         q_say="Numéro quatre. Le F cent dix-sept, l'avion furtif, n'a jamais été abattu.",
         a_say="Faux ! Un F cent dix-sept a été abattu au-dessus de la Serbie, en mille neuf cent quatre-vingt-dix-neuf.",
         a_show="Faux ! Un F-117 a été abattu au-dessus de la Serbie, en 1999."),
    dict(img='an225', stmt="L'An-225 a été conçu pour transporter une navette spatiale.", answer=0,
         q_say="Numéro cinq. L'Antonov deux cent vingt-cinq a été conçu pour transporter une navette spatiale.",
         a_say="Vrai ! Il portait sur son dos la navette soviétique Bourane.",
         a_show="Vrai ! Il portait sur son dos la navette soviétique Bourane."),
    dict(img='f22', stmt="Les États-Unis vendent le F-22 à leurs alliés.", answer=1,
         q_say="Numéro six. Les États-Unis vendent le F vingt-deux à leurs alliés.",
         a_say="Faux ! Une loi américaine interdit son exportation. Aucun autre pays n'en possède.",
         a_show="Faux ! Une loi américaine interdit son exportation. Aucun autre pays n'en possède."),
    dict(img='m2000', stmt="Le Mirage 2000 n'a pas de gouvernail de profondeur à l'arrière.", answer=0,
         q_say="Numéro sept. Le Mirage deux mille n'a pas de gouvernail de profondeur à l'arrière.",
         a_say="Vrai ! Avec son aile delta, ce sont les gouvernes de l'aile qui font monter et descendre l'avion.",
         a_show="Vrai ! Avec son aile delta, ce sont les gouvernes de l'aile qui font monter et descendre l'avion."),
    dict(img='beluga', stmt="Le Beluga d'Airbus transporte des passagers.", answer=1,
         q_say="Dernière. La plus piégeuse. Le Béluga d'Airbus transporte des passagers.",
         a_say="Faux ! Il ne transporte que des morceaux d'avions, comme des ailes et des fuselages.",
         a_show="Faux ! Il ne transporte que des morceaux d'avions, comme des ailes et des fuselages."),
]
