# Pixel art : l'effet tunnel (sources : Simons & Chabris 1999 « Gorillas in our midst » — environ la moitié ne voit pas le gorille ;
# Eastern Air Lines 401, 29/12/1972, L-1011 TriStar JFK-Miami, 176 à bord, 101 morts (NTSB : 99 + 2 décès ultérieurs), 75 survivants ;
# voyant train avant éteint (ampoule grillée, train sorti), commandant heurte le manche -> mode CWS, descente lente, carillon d'altitude non perçu,
# copilote remarque l'altitude < 10 s avant l'impact ; NTSB : échec de la surveillance des instruments pendant les 4 dernières minutes ; CRM)
SCENES = [
    dict(type='hook', title="L'EFFET TUNNEL",
         say="Ton cerveau peut te rendre aveugle. Et dans un cockpit, ça peut tuer. Ça s'appelle l'effet tunnel.",
         show="Ton cerveau peut te rendre aveugle. Et dans un cockpit, ça peut tuer. Ça s'appelle l'effet tunnel."),
    dict(type='gorilla', title="LE TEST DU GORILLE",
         say="En mille neuf cent quatre-vingt-dix-neuf, des chercheurs demandent à des gens de compter les passes dans une vidéo de basket. Au milieu, un gorille traverse l'écran. La moitié des gens ne le voient pas.",
         show="En 1999, des chercheurs demandent à des gens de compter les passes dans une vidéo de basket. Au milieu, un gorille traverse l'écran. La moitié des gens ne le voient pas."),
    dict(type='tunnel', title="LE TUNNEL",
         say="Quand ton cerveau se concentre très fort sur une seule chose, il efface tout le reste. Et le stress rend ce tunnel encore plus étroit.",
         show="Quand ton cerveau se concentre très fort sur une seule chose, il efface tout le reste. Et le stress rend ce tunnel encore plus étroit."),
    dict(type='night', title="29 DÉCEMBRE 1972",
         say="Vingt-neuf décembre mille neuf cent soixante-douze. Un TriStar d'Eastern Air Lines approche de Miami, de nuit, avec cent soixante-seize personnes à bord.",
         show="29 décembre 1972. Un TriStar d'Eastern Air Lines approche de Miami, de nuit, avec 176 personnes à bord."),
    dict(type='bulb', title="TRAIN AVANT ?",
         say="Le voyant vert du train avant ne s'allume pas. Les trois hommes du cockpit se penchent sur le problème. Tous les trois.",
         show="Le voyant vert du train avant ne s'allume pas. Les trois hommes du cockpit se penchent sur le problème. Tous les trois."),
    dict(type='descent', title="PILOTE AUTO",
         say="En se retournant, le commandant touche le manche. Le pilote automatique ne tient plus l'altitude. L'avion commence à descendre, tout doucement.",
         show="En se retournant, le commandant touche le manche. Le pilote automatique ne tient plus l'altitude. L'avion commence à descendre, tout doucement."),
    dict(type='alarm', title="ALERTE ALTITUDE",
         say="Une alarme d'altitude sonne. Personne ne réagit. Tout le monde regarde l'ampoule.",
         show="Une alarme d'altitude sonne. Personne ne réagit. Tout le monde regarde l'ampoule."),
    dict(type='crash', title="",
         say="Quand le copilote voit enfin l'altimètre, il reste moins de dix secondes. L'avion s'écrase dans les Everglades. Cent un morts.",
         show="Quand le copilote voit enfin l'altimètre, il reste moins de 10 secondes. L'avion s'écrase dans les Everglades. 101 morts."),
    dict(type='cause', title="LA CAUSE",
         say="Le train était bien sorti. Le problème, c'était une simple ampoule grillée.",
         show="Le train était bien sorti. Le problème, c'était une simple ampoule grillée."),
    dict(type='fix', title="LA RÈGLE",
         say="Depuis, les pilotes apprennent une règle simple. Quoi qu'il arrive, quelqu'un pilote l'avion. Un pilote vole, l'autre gère la panne.",
         show="Depuis, les pilotes apprennent une règle simple. Quoi qu'il arrive, quelqu'un pilote l'avion. Un pilote vole, l'autre gère la panne."),
    dict(type='verdict', title="ET TOI ?",
         say="Et toi, tu l'aurais vu, le gorille ? Abonne-toi pour d'autres histoires d'aviation.",
         show="Et toi, tu l'aurais vu, le gorille ? Abonne-toi pour d'autres histoires d'aviation."),
]
END_HOLD = 5.0
